# Generated by Django 4.1.3 on 2022-12-25 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='staff')),
                ('facebook', models.URLField()),
                ('contact', models.CharField(max_length=10)),
                ('instagram', models.CharField(blank=True, max_length=30, null=True)),

            ],
        ),
    ]
