# Generated by Django 4.1.3 on 2022-12-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('administration', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.configchoice'),
        ),
    ]
