# Generated by Django 4.1.3 on 2022-12-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_testimonials_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='position',
            new_name='profession',
        ),
    ]
