# Generated by Django 4.1.3 on 2023-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_rename_position_testimonials_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
