# Generated by Django 4.1.3 on 2022-11-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configcategory',
            options={'verbose_name_plural': 'CONFIG CATEGORY'},
        ),
        migrations.AlterModelOptions(
            name='configchoice',
            options={'verbose_name_plural': 'CONFIG CHOICE'},
        ),
    ]
