# Generated by Django 4.1.3 on 2022-11-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('name',), 'verbose_name_plural': 'USER'},
        ),
    ]
